config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|es/ do  
    devise_for :users, skip: [:sessions, :registrations]
    as :user do
      get '/', to: 'devise/sessions#new', as: :new_user_session
      post '/', to: 'devise/sessions#create', as: :user_session
      get '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get "home", to: "home#home"
    get "qrscanner", to: "home#qrscanner"
    get "kitserials", to: "home#kitserials"
    resources :home
    get "admin", to: "home#admin"
    resources :inventories
    resources :users
    put "deactive", to: "users#toggle_deactivated", as: :deactive_user
    put "elevate", to: "users#toggle_admin", as: :elevate_user
    resources :reversals
    # resource :session, only: [:new, :create, :destroy]
    resources :clients
    get "l10n_es", to: "localize#to_es", as: :l10n_es
    get "l10n_en", to: "localize#to_en", as: :l10n_en
    root to: "home#index"

    # You can also override after_sign_in_path_for and
    # after_sign_out_path_for to customize your redirect hooks.
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :client
  include PgSearch

  pg_search_scope :search_by_icounty, :associated_against => { :client => :county }
  pg_search_scope :search_by_icity, :associated_against => { :client => :city }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
    before_action :check_admin
    helper_method :sort_column, :sort_direction
    # before_action :verify_authentication

    # def index

    #     if search_params[:search_term].present?
    #         @inventories = Inventory.search_by_expiration_date(search_params[:search_term]).order("created_at DESC").page(params[:page]).per(20)
    #     else
    #         @inventories = Inventory.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    #     end
    #     # if admin show all records
    #     # if current_user.admin
    #     # @inventories = Inventory.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    #     # render json: @inventory
    #     # else
    #     # volunteer only show their own records
    #     # @inventories = Inventory.where(user_id: current_user.id)
    #     # end
    # end

    def index
        if search_params[:search_term_icounty].present?
          @inventories = Inventory.search_by_icounty(search_params[:search_term_icounty]).order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
        elsif search_params[:search_term_icity].present?
          @inventories = Inventory.search_by_icity(search_params[:search_term_icity]).order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
        else
          @inventories = Inventory.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
        end
    end

    def show
        @inventory = Inventory.find(params[:id])
        # render json: @inventory
    end
    
    # New
    
    def new
        #redirect_to inventories_path, notice: 'You must be logged in to add a new kit' if !(current_user)
         @inventory = Inventory.new   
    end

    def edit
      
      if current_user.admin
        @inventory = Inventory.find(params[:id])
      else
        redirect_to inventories_path, notice: "Error: Only an administrator can edit the inventory."
      end
    end
    
    # Create
    def create

            @inventory = Inventory.new(inventory_params)
            @inventory[:distribution_date] = Date.today
        
            if @inventory.save
              redirect_to inventories_path, notice: 'Kit was successfully recorded.'
            # render json: @inventory, notice: 'Kit was successfully recorded'
            else
                # render json: @inventory, notice: 'Error creating Kit recorded'
              render :new 
            end
    end
        
    # Update only Admin
    def update
        if current_user.admin
        @inventory = Inventory.find(params[:id])
            if @inventory.update(inventory_params)
            redirect_to inventories_path, notice: 'Kit was successfully updated.'
            #render json: @inventory, notice: 'Kit was successfully updated.'
            else
              #render json: @inventory, notice: 'Error'
              redirect_to inventories_path, notice: "Error"
            end
        else
            #render json: @inventory, notice: "you don't have access to update."
            redirect_to inventories_path, notice: "You do not have access to update the inventory."
        end
    end
        
    # DELETE only Admin
    def destroy
        # user_valid= User.find_by_email(current_user) after FE is bring screen

        if current_user.admin

        @inventory = Inventory.find(params[:id])
            @inventory.destroy
            
            #   format.html { redirect_to XXX_url, notice: 'Kit was successfully deleted.' }
            # render json: @inventory, notice: 'Kit was successfully deleted.'
            redirect_to inventories_path, notice: "Kit was successfully deleted."
        else
            # render json: @inventory, notice: "you don't have access to deleted."
            redirect_to inventories_path, notice: "Kit was successfully deleted."
        end
    end
        

    private

    def inventory_params
        params.require(:inventory).permit(:user_id, :serial_num, :kit_type, :expiration_date, :distributed_date) 
    end

    def sort_column
        sortable_columns.include?(params[:column]) ? params[:column] : "kit_type"
    end
      
    def sortable_columns
        ["kit_type", "expiration_date", "serial_num", "distributed_date", "client_id", "county", "city", "last_name"]
    end

    def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    def check_admin
        if current_user 
            redirect_to root_path unless current_user.admin?
        else
            redirect_to root_path
    end 
    end 
    
    def search_params
        params.permit(:search_term_icounty, :search_term_icity)
      end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<h2>Add a New Kit to the Inventory<h2><br>

<%= form_with model: @inventory, local:true do |form| %>

  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@inventory.errors.count, "error") %> prohibited
        this inventory from being updated:
      </h2>
      <ul>
        <% @user.inventories.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<p>  
  <%= form.label :Serial_Number %><br>
  <%= form.text_field :serial_num %> 
</p>
   
<p>
  <%= form.label :Kit_Type %><br>
  <%= form.text_field :kit_type %>
</p>

<p>
  <%= form.label :Expiration_Date %><br>
  <%= form.text_field :expiration_date %>
</p>

<p>
  <%= form.label :Distribution_Date %><br>
  <%= form.text_field :distributed_date %>
</p>

  <%= form.submit %>
<% end %>

<%= link_to '<<Back', inventories_path %> 

app/views/inventories/edit.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:head_edit_inventory) %> <i class="fas fa-medkit"></i></div>
  <div class="admin-panel">

  <%= form_with model: @inventory, local:true do |form| %>

    <% if @inventory.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@inventory.errors.count, "error") %> prohibited
          this inventory from being updated:
        </h2>
        <ul>
          <% @user.inventories.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
  <p>  
    <%= form.label t(:kit_serial) %><br>
    <%= form.text_field :serial_num %> 
  </p>
    
  <p>
    <%= form.label t(:kit_type) %><br>
    <%= form.text_field :kit_type %>
  </p>

  <p>
    <%= form.label t(:expiration_date) %><br>
    <%= form.text_field :expiration_date %>
  </p>

  <p>
    <%= form.label t(:distributed) %><br>
    <%= form.text_field :distributed_date %>
  </p>

    <%= form.submit %>
  <% end %>

  <%= link_to "#{t(:back)}", inventories_path %>

  </div>
</div>

app/views/inventories/index.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:distributed_kits) %> <i class="fas fa-medkit"></i></div>
  <div class="admin-panel">
  <div class="search-container"> 
      <%= form_tag inventories_path, method: :get do %>
      <%= select_tag :search_term_icounty, "<option>Alamance</option>
          <option>Alexander</option>
          <option>Alleghany</option>
          <option>Anson</option>
          <option>Ashe</option>
          <option>Avery</option>
          <option>Beaufort</option>
          <option>Bertie</option>
          <option>Bladen</option>
          <option>Brunswuick</option>
          <option>Buncombe</option>
          <option>Burke</option>
          <option>Cabarrus</option>
          <option>Caldwell</option>
          <option>Camden</option>
          <option>Carteret</option>
          <option>Caswell</option>
          <option>Catawba</option>
          <option>Chatham</option>
          <option>Cherokee</option>
          <option>Chowan</option>
          <option>Clay</option>
          <option>Cleveland</option>
          <option>Columbus</option>
          <option>Craven</option>
          <option>Cumberland</option>
          <option>Currituck</option>
          <option>Dare</option>
          <option>Davidson</option>
          <option>Davie</option>
          <option>Duplin</option>
          <option>Durham</option>
          <option>Edgecombe</option>
          <option>Forsyth</option>
          <option>Franklin</option>
          <option>Gaston</option>
          <option>Gates</option>
          <option>Graham</option>
          <option>Granville</option>
          <option>Greene</option>
          <option>Guilford</option>
          <option>Halifax</option>
          <option>Harnett</option>
          <option>Haywood</option>
          <option>Henderson</option>
          <option>Hertford</option>
          <option>Hoke</option>
          <option>Hyde</option>
          <option>Iredell</option>
          <option>Jackson</option>
          <option>Johnston</option>
          <option>Jones</option>
          <option>Lee</option>
          <option>Lenoir</option>
          <option>Lincoln</option>
          <option>McDowell</option>
          <option>Macon</option>
          <option>Madison</option>
          <option>Martin</option>
          <option>Mecklenburg</option>
          <option>Mitchell</option>
          <option>Montgomery</option>
          <option>Moore</option>
          <option>Nash</option>
          <option>New Hanover</option>
          <option>Northampton</option>
          <option>Onslow</option>
          <option>Orange</option>
          <option>Pamlico</option>
          <option>Pasquotank</option>
          <option>Pender</option>
          <option>Perquimans</option>
          <option>Person</option>
          <option>Pitt</option>
          <option>Polk</option>
          <option>Randolph</option>
          <option>Richmond</option>
          <option>Robeson</option>
          <option>Rockingham</option>
          <option>Rowan</option>
          <option>Rutherford</option>
          <option>Sampson</option>
          <option>Scotland</option>
          <option>Stanly</option>
          <option>Stokes</option>
          <option>Surry</option>
          <option>Swain</option>
          <option>Transylvania</option>
          <option>Tyrrell</option>
          <option>Union</option>
          <option>Vance</option>
          <option>Wake</option>
          <option>Warren</option>
          <option>Washington</option>
          <option>Watauga</option>
          <option>Wayne</option>
          <option>Wilkes</option>
          <option>Wilson</option>
          <option>Yadkin</option>
          <option>Yancey</option>", :include_blank => "#{t(:choose_county)}" %>
      <%= text_field_tag :search_term_icity, params[:search_term_icity], :placeholder => "#{t(:search_city)}" %>
      <%= submit_tag "Search"%>
      <button id="clear_search" class="btn btn-primary" onclick="window.location.href='inventories'; return false;">Clear Search</button>
      <% end %>
    </div>
  <table class="inventory-index-table">
    <tr>
      <th class="tbl-media"><%= sort_link "serial_num", "#{t(:kit_serial)}" %></th>
      <th class="tbl-media"><%= sort_link "kit_type", "#{t(:kit_type)}" %></th>
      <th class="tbl-media"><%= sort_link "expiration_date", "#{t(:expiration_date)}" %></th>
      <th class="tbl-media"><%= sort_link "distributed_date","#{t(:distributed)}" %></th>
      <th class="tbl-desktop"><%= sort_link "client_id", "#{t(:client_id)}" %></th>
      <th class="tbl-desktop"><%= t(:county) %></th>
      <th class="tbl-desktop"><%= t(:city) %></th>
      <th class="tbl-desktop tbl-media-low"><%= t(:volname) %></th>
      <th class="tbl-media"></th>
    </tr>
  
    <% @inventories.each do |inventory| %>
      <tr>
        <td class="tbl-media"><%= inventory.serial_num %></td>
        <td class="tbl-media"><%= inventory.kit_type%></td>
        <td class="tbl-media"><%= inventory.expiration_date %></td>
        <td class="tbl-media"><%= inventory.distributed_date %></td>
        <td class="tbl-desktop"><%= inventory.client_id %></td>
        <td class="tbl-desktop"><%= inventory.client.county %></td>
        <td class="tbl-desktop"><%= inventory.client.city %></td>
        <td class="tbl-desktop tbl-media-low"><%= inventory.user.first_name %> <%= inventory.user.last_name %></td>
        <td class="tbl-media"><%= link_to "#{t(:update)}", edit_inventory_path(id: inventory.id) %></td>
      </tr>
    <% end %>
  </table>
  <div class="page-index">
    <%= paginate @inventories %>
    <%= page_entries_info @inventories %>
  </div>
  <%= link_to "#{t(:back)}", admin_path %>
  </div>
</div>

app/views/inventories/new.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:add_kit) %> <i class="fas fa-medkit"></i></div>
  <div class="admin-panel">

  <%= form_with model: @inventory, local:true do |form| %>

    <% if @inventory.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@inventory.errors.count, "error") %> prohibited
          this inventory from being saved:
        </h2>
        <ul>
          <% @inventory.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
  <p>  
    <%= form.label t(:kit_serial) %><br>
    <%= form.text_field :serial_num %> 
  </p>
    
  <p>
    <%= form.label t(:kit_type) %><br>
    <%= form.text_field :kit_type %>
  </p>

  <p>
    <%= form.label t(:expiration_date) %><br>
    <%= form.text_field :expiration_date %>
  </p>

  <p>
    <%= form.label t(:distribution_date) %><br>
    <%= form.text_field :distributed_date %>
  </p>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
      <%= f.label t(:password) %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field t(:password), autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label t(:password_confirmation) %><br />
      <%= f.password_field t(:password_confirmation), autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= f.submit "#{t(:register)}" %>
    </div>
  <% end %>
    <%= form.submit %>
  <% end %>

  <%= link_to "#{t(:back)}", inventories_path %> 

  </div>
</div>

app/views/inventories/show.html.erb
<div class="admin-container">
  <div class="admin-header"> Show Inventory <i class="fas fa-medkit"></i></div>
  <div class="admin-panel">
  <p>
  <strong><%= t(:kit_serial) %></strong>
  <%= @inventory.serial_num %>
</p>
<p>
  <strong><%= t(:kit_type) %></strong>
  <%= @inventory.kit_type%>
</p>
 
<p>
  <strong><%= t(:expiration_date) %></strong>
  <%= @inventory.serial_num %>
</p>
<p>
<strong><%= t(:distributed) %></strong>
<%= @inventory.serial_num%>
</p>
<p>
<strong><%= t(:client_id) %></strong>
<%= @inventory.serial_num%>
</p>
<strong><%= t(:user_id) %></strong>
<%= @inventory.serial_num%>
</p>
<strong><%= t(:checkout) %></strong>
<%= @inventory.serial_num%>
</p>

 
<%= link_to "#{t(:update)}", edit_inventory_path(@inventory) %> |
<%= link_to "#{t(:back)}", inventories_path %>

app/views/inventories/update.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:head_update_kit) %> <i class="fas fa-medkit"></i></div>
  <div class="admin-panel">
  <%= form.label "#{t(:kit_serial)}" %><br>
        <%= form.text_field :serial_num %> 
      </p>
    
      <p>
        <%= form.label "#{t(:kit_type)}" %><br>
        <%= form.text_field :kit_type %>
      </p>
      <p>
      
    <p>
      <%= form.submit "#{t(:submit)}" %>
    </p>
  
  
  <%= link_to "#{t(:back)}", inventories_path %>

  </div>
</div>