config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|es/ do  
    devise_for :users, skip: [:sessions, :registrations]
    as :user do
      get '/', to: 'devise/sessions#new', as: :new_user_session
      post '/', to: 'devise/sessions#create', as: :user_session
      get '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get "home", to: "home#home"
    get "qrscanner", to: "home#qrscanner"
    get "kitserials", to: "home#kitserials"
    resources :home
    get "admin", to: "home#admin"
    resources :inventories
    resources :users
    put "deactive", to: "users#toggle_deactivated", as: :deactive_user
    put "elevate", to: "users#toggle_admin", as: :elevate_user
    resources :reversals
    # resource :session, only: [:new, :create, :destroy]
    resources :clients
    get "l10n_es", to: "localize#to_es", as: :l10n_es
    get "l10n_en", to: "localize#to_en", as: :l10n_en
    root to: "home#index"

    # You can also override after_sign_in_path_for and
    # after_sign_out_path_for to customize your redirect hooks.
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #For Rails 5 Devise gem, note that protect_from_forgery is no longer prepended to the before_action chain, so if you have set authenticate_user before protect_from_forgery, your request will result in "Can't verify CSRF token authenticity." To resolve this, either change the order in which you call them, or use protect_from_forgery prepend: true.
  
  has_secure_token :auth_token
  # has_secure_password
  has_many :inventories

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, format: { with: /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/ }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction

  #skip_before_action :authenticate_user! , only: [:create]
  before_action :check_admin
  before_action :set_user, only: [:show, :edit, :update, :toggle_admin, :toggle_deactivated]

  def index
    if search_params[:search_term_county].present?
      @users = User.search_by_county(search_params[:search_term_county]).order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    elsif search_params[:search_term_city].present?
      @users = User.search_by_city(search_params[:search_term_city]).order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)        
    elsif search_params[:search_term_last_name].present?
      @users = User.search_by_last_name(search_params[:search_term_last_name]).order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    else
      @users = User.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    end
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup(@user).deliver_now
      redirect_to users_path, notice: "Your account was created successfully."
    else
      render :new, notice: "Something went wrong. Please try again."
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "Your account was updated successfully."
    else
      render 'edit', notice: "Error in update."
    end
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up) do |user_params|
  #     user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
  #   end
  # end

  def toggle_deactivated
    @user.deactivated = !@user.deactivated?
    @user.save!
    redirect_to users_path
  end

  def toggle_admin
    @user.admin = !@user.admin?
    @user.save!
    redirect_to users_path
  end
  private
  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :password, :password_confirmation, :email, :phone, :county, :address1, :address2, :city, :state, :zip, :admin, :contact_type, :date_auth, :admin_auth)

  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin
    if current_user 
      redirect_to root_path unless current_user.admin?
    else
      redirect_to root_path
    end 
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "last_name"
  end
  
  def sortable_columns
    ["first_name", "last_name", "password", "email", "phone", "county", "address1", "address2", "city", "state", "zip", "admin", "contact_type", "date_auth", "admin_auth", "deactivated"]
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def search_params
    params.permit(:search_term_county, :search_term_city, :search_term_last_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
    def sort_link(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
        icon = column == sort_column ? icon : ""
        link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
      end
end

app/views/users/_form.html.erb
<%# <div class="alert alert-success mt-5" role="alert"><%= alert %>
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="has-text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with model: @user, local: true do |f| %>  
  <div class="form-field-box">
    <div class="field">
      <%= f.label t(:deactivated?) %><br />
      <%= f.check_box :deactivated %>
    </div>
    <div class="field">
      <%= f.label t(:admin?) %><br />
      <%= f.check_box :admin %>
  </div>
  </div>
  <div class="form-field-box ffb-col">
    <div class="field">
      <%= f.label t(:first_name) %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label t(:last_name) %><br />
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="form-field-box ffb-col">
    <div class="field">
      <%= f.label t(:phone) %><br />
      <%= f.phone_field :phone %>
    </div>
    <div class="field">
      <%= f.label t(:email) %><br />
      <%= f.email_field :email, autocomplete: "email" %>
    </div>
      <div class="field">
      <%= f.label t(:contact_type) %><br />
      <%= f.select(:contact_type, ['Text',
          'Phone',
          'Email'], :include_blank => "#{t(:choose_method)}") %>
    </div>
  </div>
  <div class="form-field-box ffb-col">
    <div class="field">
      <%= f.label t(:address1) %><br />
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label t(:address2) %><br />
      <%= f.text_field :address2 %>
    </div>
  </div>
  <div class="form-field-box ffb-col">
    <div class="field">
      <%= f.label t(:city) %><br />
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label t(:state) %><br />
      <%= f.text_field :state, maxlength: 2 %>
    </div>
    <div class="field">
      <%= f.label t(:zip) %><br />
      <%= f.text_field :zip, maxlength: 12 %>
    </div>
    <div class="field">
      <%= f.label t(:county) %><br />
      <%= f.select(:county, [
        'Select',
        'Alamance',
        'Alexander',
        'Alleghany',
        'Anson',
        'Ashe',
        'Avery',
        'Beaufort',
        'Bertie',
        'Bladen',
        'Brunswick',
        'Buncombe',
        'Burke',
        'Cabarrus',
        'Caldwell',
        'Camden',
        'Carteret',
        'Caswell',
        'Catawba',
        'Chatham',
        'Cherokee',
        'Chowan',
        'Clay',
        'Cleveland',
        'Columbus',
        'Craven',
        'Cumberland',
        'Currituck',
        'Dare',
        'Davidson',
        'Davie',
        'Duplin',
        'Durham',
        'Edgecombe',
        'Forsyth',
        'Franklin',
        'Gaston',
        'Gates',
        'Graham',
        'Granville',
        'Greene',
        'Guilford',
        'Halifax',
        'Harnett',
        'Haywood',
        'Henderson',
        'Hertford',
        'Hoke',
        'Hyde',
        'Iredell',
        'Jackson',
        'Johnston',
        'Jones',
        'Lee',
        'Lenoir',
        'Lincoln',
        'McDowell',
        'Macon',
        'Madison',
        'Martin',
        'Mecklenburg',
        'Mitchell',
        'Montgomery',
        'Moore',
        'Nash',
        'New Hanover',
        'Northampton',
        'Onslow',
        'Orange',
        'Pamlico',
        'Pasquotank',
        'Pender',
        'Perquimans',
        'Person',
        'Pitt',
        'Polk',
        'Randolph',
        'Richmond',
        'Robeson',
        'Rockingham',
        'Rowan',
        'Rutherford',
        'Sampson',
        'Scotland',
        'Stanly',
        'Stokes',
        'Surry',
        'Swain',
        'Transylvania',
        'Tyrrell',
        'Union',
        'Vance',
        'Wake',
        'Warren',
        'Washington',
        'Watauga',
        'Wayne',
        'Wilkes',
        'Wilson',
        'Yadkin',
        'Yancey'
        ], :include_blank => "#{t(:choose_county)}" )%>
    </div>
  </div>
  <div class="form-field-box ffb-col">
    <div class="field">
      <%= f.label t(:date_auth) %><br />
      <%= f.date_field :date_auth %>
    </div>
    <% unless @user.admin_auth %>
    <div class="field">
      <%= f.label t(:admin_auth) %><br />
      <%= f.date_field :admin_auth %>
    </div>
    <% end %>
  </div>
  <div class="form-field-box ffb-col">
    <% unless @user.id %>
    <div class="field">
      <%= f.label t(:password) %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>
    <div class="field">
      <%= f.label t(:password_confirmation) %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit "#{t(:submit)}" %>
  </div>
  <% end %>
  
  

app/views/users/edit.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:head_edit_vol) %> <i class="far fa-user"></i></div>
  <div class="admin-panel">
    <h2><%= t(:use_form_edit_vol) %><h2>

    <%= render 'form' %>

    <%= link_to "#{t(:back)}", :back %>
  </div>
</div>

app/views/users/index.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:list_vol) %> <i class="far fa-user"></i></div>
  <div class="admin-panel">
    <div class="search-container"> 
      <%= form_tag users_path, method: :get do %>
      <%= select_tag :search_term_county, "<option>Alamance</option>
          <option>Alexander</option>
          <option>Alleghany</option>
          <option>Anson</option>
          <option>Ashe</option>
          <option>Avery</option>
          <option>Beaufort</option>
          <option>Bertie</option>
          <option>Bladen</option>
          <option>Brunswuick</option>
          <option>Buncombe</option>
          <option>Burke</option>
          <option>Cabarrus</option>
          <option>Caldwell</option>
          <option>Camden</option>
          <option>Carteret</option>
          <option>Caswell</option>
          <option>Catawba</option>
          <option>Chatham</option>
          <option>Cherokee</option>
          <option>Chowan</option>
          <option>Clay</option>
          <option>Cleveland</option>
          <option>Columbus</option>
          <option>Craven</option>
          <option>Cumberland</option>
          <option>Currituck</option>
          <option>Dare</option>
          <option>Davidson</option>
          <option>Davie</option>
          <option>Duplin</option>
          <option>Durham</option>
          <option>Edgecombe</option>
          <option>Forsyth</option>
          <option>Franklin</option>
          <option>Gaston</option>
          <option>Gates</option>
          <option>Graham</option>
          <option>Granville</option>
          <option>Greene</option>
          <option>Guilford</option>
          <option>Halifax</option>
          <option>Harnett</option>
          <option>Haywood</option>
          <option>Henderson</option>
          <option>Hertford</option>
          <option>Hoke</option>
          <option>Hyde</option>
          <option>Iredell</option>
          <option>Jackson</option>
          <option>Johnston</option>
          <option>Jones</option>
          <option>Lee</option>
          <option>Lenoir</option>
          <option>Lincoln</option>
          <option>McDowell</option>
          <option>Macon</option>
          <option>Madison</option>
          <option>Martin</option>
          <option>Mecklenburg</option>
          <option>Mitchell</option>
          <option>Montgomery</option>
          <option>Moore</option>
          <option>Nash</option>
          <option>New Hanover</option>
          <option>Northampton</option>
          <option>Onslow</option>
          <option>Orange</option>
          <option>Pamlico</option>
          <option>Pasquotank</option>
          <option>Pender</option>
          <option>Perquimans</option>
          <option>Person</option>
          <option>Pitt</option>
          <option>Polk</option>
          <option>Randolph</option>
          <option>Richmond</option>
          <option>Robeson</option>
          <option>Rockingham</option>
          <option>Rowan</option>
          <option>Rutherford</option>
          <option>Sampson</option>
          <option>Scotland</option>
          <option>Stanly</option>
          <option>Stokes</option>
          <option>Surry</option>
          <option>Swain</option>
          <option>Transylvania</option>
          <option>Tyrrell</option>
          <option>Union</option>
          <option>Vance</option>
          <option>Wake</option>
          <option>Warren</option>
          <option>Washington</option>
          <option>Watauga</option>
          <option>Wayne</option>
          <option>Wilkes</option>
          <option>Wilson</option>
          <option>Yadkin</option>
          <option>Yancey</option>", :include_blank => "#{t(:choose_county)}" %>
      <%= text_field_tag :search_term_city, params[:search_term_city], :placeholder => "#{t(:search_city)}" %>
      <%= text_field_tag :search_term_last_name, params[:search_term_last_name], :placeholder => "#{t(:search_lname)}" %>
      <%= submit_tag "Search"%>
      <button id="clear_search" class="btn btn-primary" onclick="window.location.href='users'; return false;">Clear Search</button>
      <% end %>
    </div>
    <table class="volunteer-index-table">
      <tr>
        <th class="tbl-media"><%= sort_link "last_name", "#{t(:name)}" %></th>
        <th class="tbl-desktop"><%= sort_link "email", "#{t(:email)}" %></th>
        <th class="tbl-desktop tbl-media-low"><%= sort_link "phone", "#{t(:phone)}" %></th>
        <th class="tbl-desktop tbl-media-mid"><%= sort_link "contact_type", "#{t(:contact_type)}" %></th>
        <th class="tbl-media"><%= sort_link "county", "#{t(:county)}" %></th>
        <th class="tbl-desktop tbl-media-low"><%= sort_link "city", "#{t(:address)}" %></th>
        <th class="tbl-desktop tbl-media-mid"><%= sort_link "date_auth", "#{t(:date_auth)}" %></th>
        <th class="tbl-desktop tbl-media-mid"><%= sort_link "admin_auth", "#{t(:admin_auth)}" %></th>
        <th class="tbl-media"><%= sort_link "admin", "#{t(:admin)}" %></th>
        <th class="tbl-desktop"></th>
        <th class="tbl-media"><%= sort_link "deactivated", "#{t(:active)}" %></th>
      </tr>
    
      <% @users.each do |user| %>
        <tr>
          <td class="tbl-media"><%= user.first_name%><br><%= user.last_name %></td>
          <td class="tbl-desktop"><%= user.email %></td>
          <td class="tbl-desktop tbl-media-low"><%= user.phone %></td>
          <td class="tbl-desktop tbl-media-mid"><%= user.contact_type %></td>
          <td class="tbl-media"><%= user.county %></td>
          <td class="tbl-desktop tbl-media-low">
            <% if user.address1? %>
              <%= user.address1 %><br>
            <% end %>
            <% if user.address2? %>
              <%= user.address2 %><br>
            <% end %>
            <% if user.city? %>
              <%= user.city %>, 
            <% else %>
            <% end %>
            <% if user.state? %>
              <%= user.state %> 
            <% end %>
            <% if user.zip? %>
              <%= user.zip %>
            <% end %>
          <td class="tbl-desktop tbl-media-mid"><%= user.date_auth %></td>
          <td class="tbl-desktop tbl-media-mid"><%= user.admin_auth %></td>
          <td class="tbl-media"><%= link_to_if user.admin?, "", elevate_user_path(id: user.id), method: :put, class: "fas fa-user" do
              link_to "", elevate_user_path(id: user.id), method: :put, class: "fas fa-user-slash"
              end %>
          </td>
          <td class="tbl-desktop"><%= link_to 'Update', edit_user_path(id: user.id) %></td>
          <td class="tbl-media"><%= link_to_if user.deactivated?, "", deactive_user_path(id: user.id), method: :put, class: "fas fa-user-slash" do
                  link_to "", deactive_user_path(id: user.id), method: :put, class: "fas fa-user"
                  end %>
          </td>
        </tr>
        <% end %>
    </table>
    <div class="page-index">  
      <%= paginate @users %>
      <%= page_entries_info @users %>
    </div>
      <%= link_to "#{t(:back)}", admin_path %>
  </div>
</div>
      

  

app/views/users/new.html.erb
<div class="admin-container">
  <div class="admin-header"><%= t(:head_new_vol)%> <i class="far fa-user"></i></div>
  <div class="admin-panel">
    <h2><%= t(:register_new) %><h2>

    <%= render 'form' %>

    <%= link_to "#{t(:back)}", :back %>
  </div>
</div>