config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|es/ do  
    devise_for :users, skip: [:sessions, :registrations]
    as :user do
      get '/', to: 'devise/sessions#new', as: :new_user_session
      post '/', to: 'devise/sessions#create', as: :user_session
      get '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get "home", to: "home#home"
    get "qrscanner", to: "home#qrscanner"
    get "kitserials", to: "home#kitserials"
    resources :home
    get "admin", to: "home#admin"
    resources :inventories
    resources :users
    put "deactive", to: "users#toggle_deactivated", as: :deactive_user
    put "elevate", to: "users#toggle_admin", as: :elevate_user
    resources :reversals
    # resource :session, only: [:new, :create, :destroy]
    resources :clients
    get "l10n_es", to: "localize#to_es", as: :l10n_es
    get "l10n_en", to: "localize#to_en", as: :l10n_en
    root to: "home#index"

    # You can also override after_sign_in_path_for and
    # after_sign_out_path_for to customize your redirect hooks.
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # skip_before_action :verify_authentication
    def admin
    end

    def kitserials
        @status=params[:status]
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<div class="admin-container">
    <div class="admin-header"><%= t(:admin_panel) %> <i class="fas fa-user"></i></div>
    <div class="admin-panel">
        <p><%= t(:welcome) %>, <%= current_user.first_name %> <%= current_user.last_name %>!</p>
        <div class="admin-nav">
            <ul class="ap-ul">
                <li class="li-ndistro"><i class="fas fa-hands-helping"></i> <%= link_to "#{t(:naloxone_link)}", home_index_path %></li>
                <li><i class="fas fa-heartbeat"></i> Total <%= link_to "#{t(:reverse)}", reversals_path %>: <%= Reversal.all.count %></li>
                <li><i class="fas fa-medkit"></i> Total <%= link_to "#{t(:distro_nalkit)}", inventories_path %>: <%= Inventory.all.count %></li>
                <li><i class="far fa-user"></i> Total <%= link_to "#{t(:volunteers)}", users_path %>: <%= User.all.count %></li>
                <li class="li-newvol"><%= link_to "#{t(:register_new)}", new_user_path %></li>
            </ul>
        </div>
    </div>
</div>

app/views/home/home.html.erb
<%= react_component 'NaloxoneForm' %>

app/views/home/index.html.erb
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
</head>

<div class="Card-container">
  <div class="Card">
    <%= react_component 'WelcomePage', { currentUser: current_user, initialStatus: @status} , :div %>
  </div>
</div>

app/views/home/kitserials.html.erb
<%= react_component 'KitSerials', { currentUser: current_user, initialStatus: @status } , :div %>

app/views/home/qrscanner.html.erb
<%= react_component 'KitSerials', { currentUser: current_user }, :div %>